# Generated by Django 5.1.7 on 2025-03-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_view_all_tickets", "Can view all tickets")],
            },
        ),
    ]
